#ifndef SYNX_CHAINPARAMSSEEDS_H
#define SYNX_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the syndicate network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
    0x0
};

static SeedSpec6 pnSeed6_test[] = {
    0x0 
};
#endif // SYNX_CHAINPARAMSSEEDS_H
